
-- =========================
-- Base
-- =========================
CREATE TABLE "Ejercicio5"."Editorial" (
  "idEditorial" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  CONSTRAINT "EditorialPk" PRIMARY KEY ("idEditorial"),
  CONSTRAINT "EditorialNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio5"."Colegio" (
  "idColegio" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "direccion" VARCHAR(100) NOT NULL,
  "tipo" CHAR(1) NOT NULL,
  CONSTRAINT "ColegioPk" PRIMARY KEY ("idColegio"),
  CONSTRAINT "ColegioNombreUk" UNIQUE ("nombre"),
  CONSTRAINT "ColegioTipoCk" CHECK ("tipo" IN ('A','B','C'))
);

CREATE TABLE "Ejercicio5"."Aula" (
  "idAula" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(10) NOT NULL,
  CONSTRAINT "AulaPk" PRIMARY KEY ("idAula"),
  CONSTRAINT "AulaNombreUk" UNIQUE ("nombre")
);

-- =========================
-- Académico
-- =========================
CREATE TABLE "Ejercicio5"."Profesor" (
  "idProfesor" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombreCompleto" VARCHAR(50) NOT NULL,
  "cedula" NUMERIC(7) NOT NULL,
  "direccion" VARCHAR(100) NOT NULL,
  "idColegio" INTEGER NOT NULL,
  CONSTRAINT "ProfesorPk" PRIMARY KEY ("idProfesor"),
  CONSTRAINT "ProfesorColegioFk"
    FOREIGN KEY ("idColegio")
    REFERENCES "Ejercicio5"."Colegio" ("idColegio")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio5"."Asignatura" (
  "idAsignatura" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "cargaHoraria" INTEGER NOT NULL,
  "idColegio" INTEGER NOT NULL,
  CONSTRAINT "AsignaturaPk" PRIMARY KEY ("idAsignatura"),
  CONSTRAINT "AsignaturaColegioFk"
    FOREIGN KEY ("idColegio")
    REFERENCES "Ejercicio5"."Colegio" ("idColegio")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio5"."AsignaturaProfesor" (
  "idAsignatura" INTEGER NOT NULL,
  "idProfesor" INTEGER NOT NULL,
  "tipo" CHAR(1) NOT NULL,          -- T: Titular, A: Auxiliar
  "curso" VARCHAR(10) NOT NULL,
  "idAula" INTEGER NOT NULL,
  CONSTRAINT "AsignaturaProfesorPk" PRIMARY KEY ("idAsignatura", "idProfesor"),
  CONSTRAINT "AsignaturaProfesorTipoCk" CHECK ("tipo" IN ('T','A')),
  CONSTRAINT "AsignaturaProfesorAsignaturaFk"
    FOREIGN KEY ("idAsignatura")
    REFERENCES "Ejercicio5"."Asignatura" ("idAsignatura")
    ON DELETE CASCADE,
  CONSTRAINT "AsignaturaProfesorProfesorFk"
    FOREIGN KEY ("idProfesor")
    REFERENCES "Ejercicio5"."Profesor" ("idProfesor")
    ON DELETE CASCADE,
  CONSTRAINT "AsignaturaProfesorAulaFk"
    FOREIGN KEY ("idAula")
    REFERENCES "Ejercicio5"."Aula" ("idAula")
    ON DELETE RESTRICT
);

-- =========================
-- Préstamos / Libros
-- =========================
CREATE TABLE "Ejercicio5"."Prestamo" (
  "idPrestamo" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "idColegio" INTEGER NOT NULL,
  "idProfesor" INTEGER NOT NULL,
  "fechaPrestamo" DATE NOT NULL,
  "fechaDevolucion" DATE,
  "estado" VARCHAR(20) NOT NULL,
  CONSTRAINT "PrestamoPk" PRIMARY KEY ("idPrestamo"),
  CONSTRAINT "PrestamoColegioFk"
    FOREIGN KEY ("idColegio")
    REFERENCES "Ejercicio5"."Colegio" ("idColegio")
    ON DELETE RESTRICT,
  CONSTRAINT "PrestamoProfesorFk"
    FOREIGN KEY ("idProfesor")
    REFERENCES "Ejercicio5"."Profesor" ("idProfesor")
    ON DELETE RESTRICT,
  CONSTRAINT "PrestamoEstadoCk"
    CHECK ("estado" IN ('PRESTADO','DEVUELTO','VENCIDO','ANULADO'))
);

CREATE TABLE "Ejercicio5"."Libro" (
  "idLibro" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "fechaPublicacion" DATE NOT NULL,
  "disponible" BOOLEAN NOT NULL DEFAULT TRUE,
  "idPrestamo" INTEGER NOT NULL,
  CONSTRAINT "LibroPk" PRIMARY KEY ("idLibro"),
  CONSTRAINT "LibroPrestamoFk"
    FOREIGN KEY ("idPrestamo")
    REFERENCES "Ejercicio5"."Prestamo" ("idPrestamo")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio5"."LibroEditorial" (
  "idEditorial" INTEGER NOT NULL,
  "idLibro" INTEGER NOT NULL,
  CONSTRAINT "LibroEditorialPk" PRIMARY KEY ("idEditorial", "idLibro"),
  CONSTRAINT "LibroEditorialEditorialFk"
    FOREIGN KEY ("idEditorial")
    REFERENCES "Ejercicio5"."Editorial" ("idEditorial")
    ON DELETE CASCADE,
  CONSTRAINT "LibroEditorialLibroFk"
    FOREIGN KEY ("idLibro")
    REFERENCES "Ejercicio5"."Libro" ("idLibro")
    ON DELETE CASCADE
);
