

CREATE TABLE "Asignatura" (
    "idAsignatura" integer NOT NULL,
    nombre character varying(50) NOT NULL
);



ALTER TABLE "Asignatura" ALTER COLUMN "idAsignatura" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Asignatura_idAsignatura_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Aula" (
    "idAula" integer NOT NULL,
    nombre character varying(10) NOT NULL
);


ALTER TABLE "Aula" ALTER COLUMN "idAula" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Aula_idAula_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Colegio" (
    "idColegio" integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE "Colegio" ALTER COLUMN "idColegio" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Colegio_idColegio_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Curso" (
    "idCurso" integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE "Curso" ALTER COLUMN "idCurso" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Curso_idCurso_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "DetallePrestamo" (
    "idDetalle" integer NOT NULL,
    "idPrestamo" integer NOT NULL,
    cantidad integer NOT NULL,
    "idLibro" integer
);


ALTER TABLE "DetallePrestamo" ALTER COLUMN "idDetalle" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "DetallePrestamo_idDetalle_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "Editorial" (
    "idEditorial" integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE "Editorial" ALTER COLUMN "idEditorial" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Editorial_idEditorial_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Libro" (
    "idLibro" integer NOT NULL,
    nombre character varying(50) NOT NULL,
    "cantidadCopias" integer NOT NULL,
    "idEditorial" integer NOT NULL
);


ALTER TABLE "Libro" ALTER COLUMN "idLibro" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Libro_idLibro_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Prestamo" (
    "idPrestamo" integer NOT NULL,
    "fechaPrestamo" date NOT NULL,
    "idProfesor" integer NOT NULL,
    "idColegio" integer NOT NULL,
    "idAsignatura" integer NOT NULL,
    "idAula" integer NOT NULL,
    "idCurso" integer NOT NULL
);


ALTER TABLE "Prestamo" ALTER COLUMN "idPrestamo" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Prestamo_idPrestamo_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE "Profesor" (
    "idProfesor" integer NOT NULL,
    nombre character varying(50) NOT NULL,
    cedula numeric(7,0) NOT NULL
);


ALTER TABLE "Profesor" ALTER COLUMN "idProfesor" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Profesor_idProfesor_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


INSERT INTO "Asignatura" VALUES (1, 'Matematica');
INSERT INTO "Asignatura" VALUES (2, 'Lengua');
INSERT INTO "Asignatura" VALUES (3, 'Historia');
INSERT INTO "Asignatura" VALUES (39, 'Analitica');
INSERT INTO "Asignatura" VALUES (40, 'Bootcamp');
INSERT INTO "Asignatura" VALUES (41, 'Electrotecnia');


INSERT INTO "Aula" VALUES (2, 'A-02');
INSERT INTO "Aula" VALUES (3, 'B-01');
INSERT INTO "Aula" VALUES (1, 'A-03');



INSERT INTO "Colegio" VALUES (1, 'Colegio Nacional N°1');
INSERT INTO "Colegio" VALUES (2, 'Instituto Metropolitano');
INSERT INTO "Colegio" VALUES (35, 'Colegio Tecnico Nacional');


INSERT INTO "Curso" VALUES (1, '1A');
INSERT INTO "Curso" VALUES (3, '3C');
INSERT INTO "Curso" VALUES (2, 'Curso de Programación');


INSERT INTO "DetallePrestamo" VALUES (1, 1, 3, 1);
INSERT INTO "DetallePrestamo" VALUES (2, 1, 5, 2);
INSERT INTO "DetallePrestamo" VALUES (3, 1, 2, 4);
INSERT INTO "DetallePrestamo" VALUES (4, 2, 1, 2);
INSERT INTO "DetallePrestamo" VALUES (5, 2, 5, 4);


INSERT INTO "Editorial" VALUES (1, 'Kapelusz');
INSERT INTO "Editorial" VALUES (2, 'Santillana');
INSERT INTO "Editorial" VALUES (3, 'Planeta');
INSERT INTO "Editorial" VALUES (35, 'Alianza S.A');



INSERT INTO "Libro" VALUES (3, 'Historia del Universo', 11, 1);
INSERT INTO "Libro" VALUES (1, 'Algebra 1', 7, 1);
INSERT INTO "Libro" VALUES (2, 'Lectura 2', 1, 2);
INSERT INTO "Libro" VALUES (4, 'Geometria Basica', 1, 1);



INSERT INTO "Prestamo" VALUES (1, '2026-01-26', 1, 1, 3, 3, 3);
INSERT INTO "Prestamo" VALUES (2, '2026-01-26', 1, 35, 2, 3, 3);



INSERT INTO "Profesor" VALUES (1, 'Ana Gomez', 1234567);
INSERT INTO "Profesor" VALUES (2, 'Bruno Perez', 2345678);
INSERT INTO "Profesor" VALUES (3, 'Carla Diaz', 3456789);


ALTER TABLE ONLY "Asignatura"
    ADD CONSTRAINT "AsignaturaPk" PRIMARY KEY ("idAsignatura");


ALTER TABLE ONLY "Aula"
    ADD CONSTRAINT "AulaPk" PRIMARY KEY ("idAula");


ALTER TABLE ONLY "Colegio"
    ADD CONSTRAINT "ColegioPk" PRIMARY KEY ("idColegio");


ALTER TABLE ONLY "Curso"
    ADD CONSTRAINT "CursoPk" PRIMARY KEY ("idCurso");


ALTER TABLE ONLY "DetallePrestamo"
    ADD CONSTRAINT "DetallePrestamoPk" PRIMARY KEY ("idDetalle");


ALTER TABLE ONLY "Editorial"
    ADD CONSTRAINT "EditorialPk" PRIMARY KEY ("idEditorial");



ALTER TABLE ONLY "Libro"
    ADD CONSTRAINT "LibroPk" PRIMARY KEY ("idLibro");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "PrestamoPk" PRIMARY KEY ("idPrestamo");


ALTER TABLE ONLY "Profesor"
    ADD CONSTRAINT "ProfesorPk" PRIMARY KEY ("idProfesor");

CREATE INDEX idx_detalleprestamo_idlibro ON "DetallePrestamo" USING btree ("idLibro");


ALTER TABLE ONLY "DetallePrestamo"
    ADD CONSTRAINT "DetallePrestamoPrestamoFk" FOREIGN KEY ("idPrestamo") REFERENCES "Prestamo"("idPrestamo");


ALTER TABLE ONLY "Libro"
    ADD CONSTRAINT "LibroEditorialFk" FOREIGN KEY ("idEditorial") REFERENCES "Editorial"("idEditorial");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "PrestamoProfesorFk" FOREIGN KEY ("idProfesor") REFERENCES "Profesor"("idProfesor");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "fkPrestamoAsignatura" FOREIGN KEY ("idAsignatura") REFERENCES "Asignatura"("idAsignatura");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "fkPrestamoAula" FOREIGN KEY ("idAula") REFERENCES "Aula"("idAula");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "fkPrestamoColegio" FOREIGN KEY ("idColegio") REFERENCES "Colegio"("idColegio");


ALTER TABLE ONLY "Prestamo"
    ADD CONSTRAINT "fkPrestamoCurso" FOREIGN KEY ("idCurso") REFERENCES "Curso"("idCurso");


ALTER TABLE ONLY "DetallePrestamo"
    ADD CONSTRAINT fk_detalleprestamo_libro FOREIGN KEY ("idLibro") REFERENCES "Libro"("idLibro");

