
CREATE SCHEMA IF NOT EXISTS "Ejercicio5";

-- =========================
-- Base
-- =========================
CREATE TABLE IF NOT EXISTS "Ejercicio5"."Editorial" (
  "idEditorial" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"      varchar(50) NOT NULL,
  CONSTRAINT "EditorialPk" PRIMARY KEY ("idEditorial")
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."Profesor" (
  "idProfesor" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"     varchar(50) NOT NULL,
  "cedula"     numeric(7)  NOT NULL,
  CONSTRAINT "ProfesorPk" PRIMARY KEY ("idProfesor")
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."Colegio" (
  "idColegio" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"    varchar(50) NOT NULL,
  CONSTRAINT "ColegioPk" PRIMARY KEY ("idColegio")
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."Curso" (
  "idCurso" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"  varchar(50) NOT NULL,
  CONSTRAINT "CursoPk" PRIMARY KEY ("idCurso")
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."Aula" (
  "idAula" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" varchar(10) NOT NULL,
  CONSTRAINT "AulaPk" PRIMARY KEY ("idAula")
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."Asignatura" (
  "idAsignatura" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"       varchar(50) NOT NULL,
  CONSTRAINT "AsignaturaPk" PRIMARY KEY ("idAsignatura")
);

-- =========================
-- Libros
-- =========================
CREATE TABLE IF NOT EXISTS "Ejercicio5"."Libro" (
  "idLibro"        integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre"         varchar(50) NOT NULL,
  "cantidadCopias" integer NOT NULL,
  "idEditorial"    integer NOT NULL,
  CONSTRAINT "LibroPk" PRIMARY KEY ("idLibro"),
  CONSTRAINT "LibroEditorialFk"
    FOREIGN KEY ("idEditorial")
    REFERENCES "Ejercicio5"."Editorial" ("idEditorial")
    ON DELETE NO ACTION
);

-- =========================
-- Prestamos
-- =========================
CREATE TABLE IF NOT EXISTS "Ejercicio5"."Prestamo" (
  "idPrestamo"    integer GENERATED BY DEFAULT AS IDENTITY,
  "fechaPrestamo" date NOT NULL,
  "idProfesor"    integer NOT NULL,
  CONSTRAINT "PrestamoPk" PRIMARY KEY ("idPrestamo"),
  CONSTRAINT "PrestamoProfesorFk"
    FOREIGN KEY ("idProfesor")
    REFERENCES "Ejercicio5"."Profesor" ("idProfesor")
    ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Ejercicio5"."DetallePrestamo" (
  "idDetalle"  integer GENERATED BY DEFAULT AS IDENTITY,
  "idPrestamo" integer NOT NULL,
  "cantidad"   varchar NOT NULL,
  CONSTRAINT "DetallePrestamoPk" PRIMARY KEY ("idDetalle"),
  CONSTRAINT "DetallePrestamoPrestamoFk"
    FOREIGN KEY ("idPrestamo")
    REFERENCES "Ejercicio5"."Prestamo" ("idPrestamo")
    ON DELETE NO ACTION
);

-- Puente N-M entre DetallePrestamo y Libro
CREATE TABLE IF NOT EXISTS "Ejercicio5"."PrestamoLibro" (
  "idDetalle" integer NOT NULL,
  "idLibro"   integer NOT NULL,
  CONSTRAINT "PrestamoLibroPk" PRIMARY KEY ("idDetalle", "idLibro"),
  CONSTRAINT "PrestamoLibroDetalleFk"
    FOREIGN KEY ("idDetalle")
    REFERENCES "Ejercicio5"."DetallePrestamo" ("idDetalle")
    ON DELETE NO ACTION,
  CONSTRAINT "PrestamoLibroLibroFk"
    FOREIGN KEY ("idLibro")
    REFERENCES "Ejercicio5"."Libro" ("idLibro")
    ON DELETE NO ACTION
);

-- =========================
-- Asignaciones (PFK + FK)
-- =========================
CREATE TABLE IF NOT EXISTS "Ejercicio5"."AsignacionProfesor" (
  "idColegio"    integer NOT NULL,
  "idAsignatura" integer NOT NULL,
  "idAula"       integer NOT NULL,
  "idCurso"      integer NOT NULL,
  "idProfesor"   integer NOT NULL,

  CONSTRAINT "AsignacionProfesorPk"
    PRIMARY KEY ("idColegio", "idAsignatura", "idAula", "idCurso"),

  CONSTRAINT "AsignacionProfesorColegioFk"
    FOREIGN KEY ("idColegio")
    REFERENCES "Ejercicio5"."Colegio" ("idColegio")
    ON DELETE NO ACTION,

  CONSTRAINT "AsignacionProfesorAsignaturaFk"
    FOREIGN KEY ("idAsignatura")
    REFERENCES "Ejercicio5"."Asignatura" ("idAsignatura")
    ON DELETE NO ACTION,

  CONSTRAINT "AsignacionProfesorAulaFk"
    FOREIGN KEY ("idAula")
    REFERENCES "Ejercicio5"."Aula" ("idAula")
    ON DELETE NO ACTION,

  CONSTRAINT "AsignacionProfesorCursoFk"
    FOREIGN KEY ("idCurso")
    REFERENCES "Ejercicio5"."Curso" ("idCurso")
    ON DELETE NO ACTION,

  CONSTRAINT "AsignacionProfesorProfesorFk"
    FOREIGN KEY ("idProfesor")
    REFERENCES "Ejercicio5"."Profesor" ("idProfesor")
    ON DELETE NO ACTION
);
