CREATE SCHEMA IF NOT EXISTS "Ejercicio3";

-- =========================
-- 1) Ubicación
-- =========================
CREATE TABLE "Ejercicio3"."Pais" (
  "idPais" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  CONSTRAINT "PaisPk" PRIMARY KEY ("idPais"),
  CONSTRAINT "PaisNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio3"."ProvinciaEstado" (
  "idProvincia" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "idPais" INTEGER NOT NULL,
  CONSTRAINT "ProvinciaEstadoPk" PRIMARY KEY ("idProvincia"),
  CONSTRAINT "ProvinciaEstadoPaisFk" FOREIGN KEY ("idPais")
    REFERENCES "Ejercicio3"."Pais" ("idPais")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "ProvinciaEstadoUk" UNIQUE ("nombre", "idPais")
);

CREATE TABLE "Ejercicio3"."Ciudad" (
  "idCiudad" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "codigoPostal" VARCHAR(15) NOT NULL,
  "idProvincia" INTEGER NOT NULL,
  CONSTRAINT "CiudadPk" PRIMARY KEY ("idCiudad"),
  CONSTRAINT "CiudadProvinciaEstadoFk" FOREIGN KEY ("idProvincia")
    REFERENCES "Ejercicio3"."ProvinciaEstado" ("idProvincia")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "CiudadCodigoPostalUk" UNIQUE ("codigoPostal"),
  CONSTRAINT "CiudadNombreUk" UNIQUE ("nombre", "idProvincia")
);

-- =========================
-- 2) Actividad y empresa origen
-- =========================
CREATE TABLE "Ejercicio3"."ActividadComercial" (
  "idActividad" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "descripcion" VARCHAR(200) NOT NULL,
  "nombre" VARCHAR(20) NOT NULL,
  CONSTRAINT "ActividadComercialPk" PRIMARY KEY ("idActividad"),
  CONSTRAINT "ActividadComercialNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio3"."Empresa" (
  "idEmpresa" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "idActividad" INTEGER NOT NULL,
  "ruc" VARCHAR(10) NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  CONSTRAINT "EmpresaPk" PRIMARY KEY ("idEmpresa"),
  CONSTRAINT "EmpresaActividadFk" FOREIGN KEY ("idActividad")
    REFERENCES "Ejercicio3"."ActividadComercial" ("idActividad")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "EmpresaRucUk" UNIQUE ("ruc")
);

-- =========================
-- 3) Destinatario
-- =========================
CREATE TABLE "Ejercicio3"."Destinatario" (
  "idDestinatario" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  CONSTRAINT "DestinatarioPk" PRIMARY KEY ("idDestinatario")
);

-- =========================
-- 4) Guía (cabecera)
-- =========================
CREATE TABLE "Ejercicio3"."Guia" (
  "idGuia" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "numeroGuia" NUMERIC(20,0) NOT NULL,
  "fecha" DATE NOT NULL,
  "hora" TIME NOT NULL,
  "distanciaKilometraje" VARCHAR(20) NOT NULL,
  "idDestinatario" INTEGER NOT NULL,
  "idEmpresa" INTEGER NOT NULL,
  "valorFlete" NUMERIC(10,0) NOT NULL, 
  CONSTRAINT "GuiaPk" PRIMARY KEY ("idGuia"),
  CONSTRAINT "GuiaNumeroUk" UNIQUE ("numeroGuia"),
  CONSTRAINT "GuiaDestinatarioFk" FOREIGN KEY ("idDestinatario")
    REFERENCES "Ejercicio3"."Destinatario" ("idDestinatario")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "GuiaEmpresaFk" FOREIGN KEY ("idEmpresa")
    REFERENCES "Ejercicio3"."Empresa" ("idEmpresa")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

-- =========================
-- 5) Catálogos de paquete y flete
-- =========================
CREATE TABLE "Ejercicio3"."Tipo" (
  "idTipo" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  CONSTRAINT "TipoPk" PRIMARY KEY ("idTipo"),
  CONSTRAINT "TipoNombreUk" UNIQUE ("nombre")
);


-- =========================
-- 6) Paquete (detalle por guía)
-- =========================
CREATE TABLE "Ejercicio3"."Paquete" (
  "idPaquete" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" VARCHAR(20) NOT NULL,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  "idTipo" INTEGER NOT NULL,
  "idGuia" INTEGER NOT NULL,
  "idValor" INTEGER NOT NULL,
  CONSTRAINT "PaquetePk" PRIMARY KEY ("idPaquete"),
  CONSTRAINT "PaqueteCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "PaqueteTipoFk" FOREIGN KEY ("idTipo")
    REFERENCES "Ejercicio3"."Tipo" ("idTipo")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "PaqueteGuiaFk" FOREIGN KEY ("idGuia")
    REFERENCES "Ejercicio3"."Guia" ("idGuia")
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);

-- =========================
-- 7) Dirección y teléfono
-- =========================
CREATE TABLE "Ejercicio3"."Direccion" (
  "idDireccion" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "idCiudad" INTEGER NOT NULL,
  "idEmpresa" INTEGER NOT NULL,
  "idDestinatario" INTEGER NOT NULL,
  CONSTRAINT "DireccionPk" PRIMARY KEY ("idDireccion"),
  CONSTRAINT "DireccionCiudadFk" FOREIGN KEY ("idCiudad")
    REFERENCES "Ejercicio3"."Ciudad" ("idCiudad")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT "DireccionEmpresaFk" FOREIGN KEY ("idEmpresa")
    REFERENCES "Ejercicio3"."Empresa" ("idEmpresa")
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT "DireccionDestinatarioFk" FOREIGN KEY ("idDestinatario")
    REFERENCES "Ejercicio3"."Destinatario" ("idDestinatario")
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);

CREATE TABLE "Ejercicio3"."TipoContacto" (
  "idTipoContacto" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  CONSTRAINT "TipoContactoPk" PRIMARY KEY ("idTipoContacto")
);

CREATE TABLE "Ejercicio3"."Contacto" (
  "idContacto" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "dato" VARCHAR(20) NOT NULL,
  "esActivo" BOOLEAN NOT NULL DEFAULT TRUE,
  "observacion" VARCHAR(100),
  "idEmpresa" INTEGER NOT NULL,
  "idDestinatario" INTEGER NOT NULL,
  "idTipoContacto" INTEGER NOT NULL,
  CONSTRAINT "ContactoPk" PRIMARY KEY ("idContacto"),
  CONSTRAINT "ContactoEmpresaFk" FOREIGN KEY ("idEmpresa")
    REFERENCES "Ejercicio3"."Empresa" ("idEmpresa")
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT "ContactoDestinatarioFk" FOREIGN KEY ("idDestinatario")
    REFERENCES "Ejercicio3"."Destinatario" ("idDestinatario")
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT "ContactoTipoFk" FOREIGN KEY ("idTipoContacto")
    REFERENCES "Ejercicio3"."TipoContacto" ("idTipoContacto")
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
