CREATE SCHEMA IF NOT EXISTS "Ejercicio4";

-- =========================
-- Catálogos
-- =========================
CREATE TABLE "Ejercicio4"."TipoContacto" (
  "idTipoContacto" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  CONSTRAINT "TipoContactoPk" PRIMARY KEY ("idTipoContacto"),
  CONSTRAINT "TipoContactoNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio4"."CategoriaPelicula" (
  "idCategoria" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  CONSTRAINT "CategoriaPeliculaPk" PRIMARY KEY ("idCategoria"),
  CONSTRAINT "CategoriaPeliculaNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio4"."FormatoCasete" (
  "idFormato" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  CONSTRAINT "FormatoCasetePk" PRIMARY KEY ("idFormato"),
  CONSTRAINT "FormatoCaseteNombreUk" UNIQUE ("nombre")
);

-- =========================
-- Cliente / Contacto / Dirección
-- =========================
CREATE TABLE "Ejercicio4"."Cliente" (
  "idCliente" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "apellido" VARCHAR(50) NOT NULL,
  "numeroMembresia" INTEGER NOT NULL,
  "esMiembroActivo" BOOLEAN NOT NULL,
  CONSTRAINT "ClientePk" PRIMARY KEY ("idCliente"),
  CONSTRAINT "ClienteNumeroMembresiaUk" UNIQUE ("numeroMembresia")
);

CREATE TABLE "Ejercicio4"."Contacto" (
  "idContacto" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "dato" VARCHAR(30) NOT NULL,
  "idTipoContacto" INTEGER NOT NULL,
  "idCliente" INTEGER NOT NULL,
  CONSTRAINT "ContactoPk" PRIMARY KEY ("idContacto"),
  CONSTRAINT "ContactoTipoContactoFk"
    FOREIGN KEY ("idTipoContacto")
    REFERENCES "Ejercicio4"."TipoContacto" ("idTipoContacto")
    ON DELETE RESTRICT,
  CONSTRAINT "ContactoClienteFk"
    FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio4"."Cliente" ("idCliente")
    ON DELETE CASCADE
);

CREATE TABLE "Ejercicio4"."Direccion" (
  "idDireccion" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "ciudad" VARCHAR(20) NOT NULL,
  "pais" VARCHAR(20) NOT NULL,
  "idCliente" INTEGER NOT NULL,
  CONSTRAINT "DireccionPk" PRIMARY KEY ("idDireccion"),
  CONSTRAINT "DireccionClienteFk"
    FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio4"."Cliente" ("idCliente")
    ON DELETE CASCADE
);

-- =========================
-- Películas / Actores
-- =========================
CREATE TABLE "Ejercicio4"."Pelicula" (
  "idPelicula" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "titulo" VARCHAR(50) NOT NULL,
  "idCategoria" INTEGER NOT NULL,
  CONSTRAINT "PeliculaPk" PRIMARY KEY ("idPelicula"),
  CONSTRAINT "PeliculaCategoriaFk"
    FOREIGN KEY ("idCategoria")
    REFERENCES "Ejercicio4"."CategoriaPelicula" ("idCategoria")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio4"."Actor" (
  "idActor" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombreArtistico" VARCHAR(50) NOT NULL,
  "nombreReal" VARCHAR(50) NOT NULL,
  "fechaNacimiento" DATE NOT NULL,
  CONSTRAINT "ActorPk" PRIMARY KEY ("idActor")
);

CREATE TABLE "Ejercicio4"."ActorPelicula" (
  "idPelicula" INTEGER NOT NULL,
  "idActor" INTEGER NOT NULL,
  CONSTRAINT "ActorPeliculaPk" PRIMARY KEY ("idPelicula", "idActor"),
  CONSTRAINT "ActorPeliculaPeliculaFk"
    FOREIGN KEY ("idPelicula")
    REFERENCES "Ejercicio4"."Pelicula" ("idPelicula")
    ON DELETE CASCADE,
  CONSTRAINT "ActorPeliculaActorFk"
    FOREIGN KEY ("idActor")
    REFERENCES "Ejercicio4"."Actor" ("idActor")
    ON DELETE CASCADE
);

-- =========================
-- Casetes
-- =========================
CREATE TABLE "Ejercicio4"."Casete" (
  "idCasete" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" NUMERIC(15) NOT NULL,
  "numeroCopias" INTEGER NOT NULL,
  "idPelicula" INTEGER NOT NULL,
  "idFormato" INTEGER NOT NULL,
  CONSTRAINT "CasetePk" PRIMARY KEY ("idCasete"),
  CONSTRAINT "CaseteCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "CasetePeliculaFk"
    FOREIGN KEY ("idPelicula")
    REFERENCES "Ejercicio4"."Pelicula" ("idPelicula")
    ON DELETE RESTRICT,
  CONSTRAINT "CaseteFormatoFk"
    FOREIGN KEY ("idFormato")
    REFERENCES "Ejercicio4"."FormatoCasete" ("idFormato")
    ON DELETE RESTRICT
);

-- =========================
-- Alquiler
-- =========================
CREATE TABLE "Ejercicio4"."Alquiler" (
  "idAlquiler" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" NUMERIC(15) NOT NULL,
  "fechaAlquiler" DATE NOT NULL,
  "fechaDevolucion" DATE NOT NULL,
  "valorAlquiler" NUMERIC NOT NULL,
  "cantPeliAlquilada" INTEGER NOT NULL,
  "idCliente" INTEGER NOT NULL,
  CONSTRAINT "AlquilerPk" PRIMARY KEY ("idAlquiler"),
  CONSTRAINT "AlquilerCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "AlquilerClienteFk"
    FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio4"."Cliente" ("idCliente")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio4"."AlquilerCasete" (
  "idAlquiler" INTEGER NOT NULL,
  "idCasete" INTEGER NOT NULL,
  CONSTRAINT "AlquilerCasetePk" PRIMARY KEY ("idAlquiler", "idCasete"),
  CONSTRAINT "AlquilerCaseteAlquilerFk"
    FOREIGN KEY ("idAlquiler")
    REFERENCES "Ejercicio4"."Alquiler" ("idAlquiler")
    ON DELETE CASCADE,
  CONSTRAINT "AlquilerCaseteCaseteFk"
    FOREIGN KEY ("idCasete")
    REFERENCES "Ejercicio4"."Casete" ("idCasete")
    ON DELETE RESTRICT
);
