

CREATE TABLE "Ejercicio7"."Editorial" (
  "idEditorial" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(30) NOT NULL,
  CONSTRAINT "EditorialPk" PRIMARY KEY ("idEditorial"),
  CONSTRAINT "EditorialNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio7"."Autor" (
  "idAutor" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  CONSTRAINT "AutorPk" PRIMARY KEY ("idAutor"),
  CONSTRAINT "AutorNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio7"."Lector" (
  "idLector" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombreCompleto" VARCHAR(50) NOT NULL,
  CONSTRAINT "LectorPk" PRIMARY KEY ("idLector")
);

CREATE TABLE "Ejercicio7"."Libro" (
  "idLibro" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "titulo" VARCHAR(50) NOT NULL,
  "codigo" VARCHAR(10) NOT NULL,
  "disponible" BOOLEAN NOT NULL DEFAULT TRUE,
  "idAutor" INTEGER NOT NULL,
  "idEditorial" INTEGER NOT NULL,
  CONSTRAINT "LibroPk" PRIMARY KEY ("idLibro"),
  CONSTRAINT "LibroCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "LibroAutorFk"
    FOREIGN KEY ("idAutor")
    REFERENCES "Ejercicio7"."Autor" ("idAutor")
    ON DELETE RESTRICT,
  CONSTRAINT "LibroEditorialFk"
    FOREIGN KEY ("idEditorial")
    REFERENCES "Ejercicio7"."Editorial" ("idEditorial")
    ON DELETE RESTRICT
);

CREATE TABLE "Ejercicio7"."Prestamo" (
  "idPrestamo" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "fechaDevolucion" DATE NOT NULL,
  "idLector" INTEGER NOT NULL,
  "idLibro" INTEGER NOT NULL,
  CONSTRAINT "PrestamoPk" PRIMARY KEY ("idPrestamo"),
  CONSTRAINT "PrestamoLectorFk"
    FOREIGN KEY ("idLector")
    REFERENCES "Ejercicio7"."Lector" ("idLector")
    ON DELETE RESTRICT,
  CONSTRAINT "PrestamoLibroFk"
    FOREIGN KEY ("idLibro")
    REFERENCES "Ejercicio7"."Libro" ("idLibro")
    ON DELETE RESTRICT
);
