
-- =========================
-- Tablas base
-- =========================
CREATE TABLE "Ejercicio6"."Seccion" (
  "idSeccion" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" CHAR(1) NOT NULL,
  "nombre" VARCHAR(20) NOT NULL,
  CONSTRAINT "SeccionPk" PRIMARY KEY ("idSeccion"),
  CONSTRAINT "SeccionCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "SeccionNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio6"."Oficina" (
  "idOficina" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(40) NOT NULL,
  "codigo" VARCHAR(10) NOT NULL,
  CONSTRAINT "OficinaPk" PRIMARY KEY ("idOficina"),
  CONSTRAINT "OficinaCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "OficinaNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio6"."Docente" (
  "idDocente" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  CONSTRAINT "DocentePk" PRIMARY KEY ("idDocente"),
  CONSTRAINT "DocenteNombreUk" UNIQUE ("nombre")
);

CREATE TABLE "Ejercicio6"."Especialidad" (
  "idEspecialidad" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(20) NOT NULL,
  CONSTRAINT "EspecialidadPk" PRIMARY KEY ("idEspecialidad"),
  CONSTRAINT "EspecialidadNombreUk" UNIQUE ("nombre")
);

-- =========================
-- Alumno
-- =========================
CREATE TABLE "Ejercicio6"."Alumno" (
  "idAlumno" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" VARCHAR(10) NOT NULL,
  "nombreCompleto" VARCHAR(50) NOT NULL,
  "idEspecialidad" INTEGER NOT NULL,
  CONSTRAINT "AlumnoPk" PRIMARY KEY ("idAlumno"),
  CONSTRAINT "AlumnoCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "AlumnoEspecialidadFk"
    FOREIGN KEY ("idEspecialidad")
    REFERENCES "Ejercicio6"."Especialidad" ("idEspecialidad")
    ON DELETE RESTRICT
);

-- =========================
-- Curso
-- =========================
CREATE TABLE "Ejercicio6"."Curso" (
  "idCurso" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" VARCHAR(10) NOT NULL,
  "nombre" VARCHAR(20) NOT NULL,
  "idSeccion" INTEGER NOT NULL,
  "idOficina" INTEGER NOT NULL,
  "idDocente" INTEGER NOT NULL,
  CONSTRAINT "CursoPk" PRIMARY KEY ("idCurso"),
  CONSTRAINT "CursoCodigoUk" UNIQUE ("codigo"),
  CONSTRAINT "CursoNombreUk" UNIQUE ("nombre"),
  CONSTRAINT "CursoSeccionFk"
    FOREIGN KEY ("idSeccion")
    REFERENCES "Ejercicio6"."Seccion" ("idSeccion")
    ON DELETE RESTRICT,
  CONSTRAINT "CursoOficinaFk"
    FOREIGN KEY ("idOficina")
    REFERENCES "Ejercicio6"."Oficina" ("idOficina")
    ON DELETE RESTRICT,
  CONSTRAINT "CursoDocenteFk"
    FOREIGN KEY ("idDocente")
    REFERENCES "Ejercicio6"."Docente" ("idDocente")
    ON DELETE RESTRICT
);

-- =========================
-- ReporteMatricula
-- =========================
CREATE TABLE "Ejercicio6"."ReporteMatricula" (
  "idReporte" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "numero" INTEGER NOT NULL,
  "idCurso" INTEGER NOT NULL,
  "idAlumno" INTEGER NOT NULL,
  CONSTRAINT "ReporteMatriculaPk" PRIMARY KEY ("idReporte"),
  CONSTRAINT "ReporteMatriculaCursoFk"
    FOREIGN KEY ("idCurso")
    REFERENCES "Ejercicio6"."Curso" ("idCurso")
    ON DELETE CASCADE,
  CONSTRAINT "ReporteMatriculaAlumnoFk"
    FOREIGN KEY ("idAlumno")
    REFERENCES "Ejercicio6"."Alumno" ("idAlumno")
    ON DELETE CASCADE,
  CONSTRAINT "ReporteMatriculaUk" UNIQUE ("idCurso", "idAlumno")
);
