-- =========================
-- TABLAS (PK con IDENTITY)
-- =========================

CREATE TABLE Pais (
  idPais INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  CONSTRAINT pais_pk PRIMARY KEY (idPais)
);

CREATE TABLE ProvinciaEstado (
  idProvincia INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  idPais INTEGER NOT NULL,
  CONSTRAINT provinciaestado_pk PRIMARY KEY (idProvincia),
  CONSTRAINT pais_provinciaestado_fk FOREIGN KEY (idPais)
    REFERENCES Pais (idPais)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX provinciaestado_idx
  ON ProvinciaEstado (nombre, idPais);

CREATE TABLE Ciudad (
  idCiudad INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  idProvincia INTEGER NOT NULL,
  CONSTRAINT ciudad_pk PRIMARY KEY (idCiudad),
  CONSTRAINT provinciaestado_ciudad_fk FOREIGN KEY (idProvincia)
    REFERENCES ProvinciaEstado (idProvincia)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX ciudad_idx
  ON Ciudad (nombre, idProvincia);

CREATE TABLE CategoriaProducto (
  idCategoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(30) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  CONSTRAINT categoriaproducto_pk PRIMARY KEY (idCategoria)
);

CREATE TABLE Producto (
  idProducto INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo VARCHAR(15) NOT NULL,
  descripcion VARCHAR(200) NOT NULL,
  precio INTEGER NOT NULL,
  idCategoria INTEGER NOT NULL,
  CONSTRAINT producto_pk PRIMARY KEY (idProducto),
  CONSTRAINT categoria_producto_producto_fk FOREIGN KEY (idCategoria)
    REFERENCES CategoriaProducto (idCategoria)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE Cliente (
  idCliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  ruc VARCHAR(9) NOT NULL,
  CONSTRAINT cliente_pk PRIMARY KEY (idCliente)
);

CREATE TABLE Direccion (
  idDireccion INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  idCliente INTEGER NOT NULL,
  idCiudad INTEGER NOT NULL,
  CONSTRAINT direccion_pk PRIMARY KEY (idDireccion),
  CONSTRAINT cliente_direccion_fk FOREIGN KEY (idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT ciudad_direccion_fk FOREIGN KEY (idCiudad)
    REFERENCES Ciudad (idCiudad)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE Telefono (
  idTelefono INTEGER GENERATED BY DEFAULT AS IDENTITY,
  numero VARCHAR(20) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  esActivo BOOLEAN NOT NULL DEFAULT true,
  observacion VARCHAR(100),
  idCliente INTEGER NOT NULL,
  CONSTRAINT telefono_pk PRIMARY KEY (idTelefono),
  CONSTRAINT cliente_telefono_fk FOREIGN KEY (idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);

CREATE TABLE Factura (
  idFactura INTEGER GENERATED BY DEFAULT AS IDENTITY,
  numero INTEGER NOT NULL,
  fechaEmision DATE NOT NULL,
  idCliente INTEGER NOT NULL,
  CONSTRAINT factura_pk PRIMARY KEY (idFactura),
  CONSTRAINT cliente_factura_fk FOREIGN KEY (idCliente)
    REFERENCES Cliente (idCliente)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE DetalleFactura (
  idDetalle INTEGER GENERATED BY DEFAULT AS IDENTITY,
  cantidad_comprada INTEGER NOT NULL,
  idFactura INTEGER NOT NULL,
  idProducto INTEGER NOT NULL,
  CONSTRAINT detallefactura_pk PRIMARY KEY (idDetalle),
  CONSTRAINT factura_detalle_factura_fk FOREIGN KEY (idFactura)
    REFERENCES Factura (idFactura)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT producto_detalle_factura_fk FOREIGN KEY (idProducto)
    REFERENCES Producto (idProducto)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);
