CREATE SCHEMA IF NOT EXISTS "Ejercicio2";


CREATE TABLE "Ejercicio2"."Pais" (
  "idPais" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  CONSTRAINT "PaisPk" PRIMARY KEY ("idPais")
);

CREATE TABLE "Ejercicio2"."ProvinciaEstado" (
  "idProvincia" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "idPais" INTEGER NOT NULL,
  CONSTRAINT "ProvinciaEstadoPk" PRIMARY KEY ("idProvincia"),
  CONSTRAINT "PaisProvinciaEstadoFk" FOREIGN KEY ("idPais")
    REFERENCES "Ejercicio2"."Pais" ("idPais")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "ProvinciaEstadoIdx"
  ON "Ejercicio2"."ProvinciaEstado" ("nombre", "idPais");

CREATE TABLE "Ejercicio2"."Ciudad" (
  "idCiudad" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "idProvincia" INTEGER NOT NULL,
  CONSTRAINT "CiudadPk" PRIMARY KEY ("idCiudad"),
  CONSTRAINT "ProvinciaEstadoCiudadFk" FOREIGN KEY ("idProvincia")
    REFERENCES "Ejercicio2"."ProvinciaEstado" ("idProvincia")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX "CiudadIdx"
  ON "Ejercicio2"."Ciudad" ("nombre", "idProvincia");

CREATE TABLE "Ejercicio2"."CategoriaProducto" (
  "idCategoria" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(30) NOT NULL,
  "descripcion" VARCHAR(100) NOT NULL,
  CONSTRAINT "CategoriaProductoPk" PRIMARY KEY ("idCategoria")
);

CREATE TABLE "Ejercicio2"."Producto" (
  "idProducto" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "codigo" VARCHAR(15) NOT NULL,
  "descripcion" VARCHAR(200) NOT NULL,
  "precio" INTEGER NOT NULL,
  "idCategoria" INTEGER NOT NULL,
  CONSTRAINT "ProductoPk" PRIMARY KEY ("idProducto"),
  CONSTRAINT "CategoriaProductoProductoFk" FOREIGN KEY ("idCategoria")
    REFERENCES "Ejercicio2"."CategoriaProducto" ("idCategoria")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE "Ejercicio2"."Cliente" (
  "idCliente" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "ruc" VARCHAR(9) NOT NULL,
  CONSTRAINT "ClientePk" PRIMARY KEY ("idCliente")
);

CREATE TABLE "Ejercicio2"."Direccion" (
  "idDireccion" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nombre" VARCHAR(50) NOT NULL,
  "idCliente" INTEGER NOT NULL,
  "idCiudad" INTEGER NOT NULL,
  CONSTRAINT "DireccionPk" PRIMARY KEY ("idDireccion"),
  CONSTRAINT "ClienteDireccionFk" FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio2"."Cliente" ("idCliente")
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT "CiudadDireccionFk" FOREIGN KEY ("idCiudad")
    REFERENCES "Ejercicio2"."Ciudad" ("idCiudad")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE "Ejercicio2"."Telefono" (
  "idTelefono" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "numero" VARCHAR(20) NOT NULL,
  "tipo" VARCHAR(20) NOT NULL,
  "esActivo" BOOLEAN NOT NULL DEFAULT TRUE,
  "observacion" VARCHAR(100),
  "idCliente" INTEGER NOT NULL,
  CONSTRAINT "TelefonoPk" PRIMARY KEY ("idTelefono"),
  CONSTRAINT "ClienteTelefonoFk" FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio2"."Cliente" ("idCliente")
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);

CREATE TABLE "Ejercicio2"."Factura" (
  "idFactura" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "numero" INTEGER NOT NULL,
  "fechaEmision" DATE NOT NULL,
  "idCliente" INTEGER NOT NULL,
  CONSTRAINT "FacturaPk" PRIMARY KEY ("idFactura"),
  CONSTRAINT "ClienteFacturaFk" FOREIGN KEY ("idCliente")
    REFERENCES "Ejercicio2"."Cliente" ("idCliente")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE "Ejercicio2"."DetalleFactura" (
  "idDetalle" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "cantidadComprada" INTEGER NOT NULL,
  "idFactura" INTEGER NOT NULL,
  "idProducto" INTEGER NOT NULL,
  CONSTRAINT "DetalleFacturaPk" PRIMARY KEY ("idDetalle"),
  CONSTRAINT "FacturaDetalleFacturaFk" FOREIGN KEY ("idFactura")
    REFERENCES "Ejercicio2"."Factura" ("idFactura")
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT "ProductoDetalleFacturaFk" FOREIGN KEY ("idProducto")
    REFERENCES "Ejercicio2"."Producto" ("idProducto")
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);
